### ISSUE TITLE
كلمة شكر

### ISSUE THREAD

**Issue by SafaAlfulaij** [Hamza5/Learn-to-program-with-C_AR#34]
ما شاء الله تبارك الرحمن
أحسنتم في صناعة هذا المحتوى الممتاز الذي قلما نجد مثله في الساحة العربية
تحياتي لكم جميعا وأعتذر عن فتح هذه العلة :)

ملاحظة: يبدو أنني سأستعين بهذا الكتاب لإشباع معرفتي عن لاتخ

**Comment by Hamza5** [comment]
<div dir='rtl'>

شكرا لك على التشجيع و تأمل أن تكون هذه البداية فقط.

شفرة LaTeX الّتي كتبتها قد لا تكون مساعدة لك، لأنها لا تحتوي على تعليقات بشكل كافي كما أنّها مليئة بالأوامر المعاد تعريفها الّتي حتى أنا نسيت سبب وضع بعضها بذلك الشكل، هذا لأنّي لست محترفا في LaTeX و في كل مرة أتوقف عن العمل به لمدة طويلة قبل أن أعود إليه. حسنا، لكن لا أحد سيمنعك من استخدامها إن أردت. 

بعد إذنك، سأغلق هذه العلّة لأنها لا تحتوي على مشكل يجب معالجته.

</div>
