### ISSUE TITLE
مشكلة في الفهرس

### ISSUE THREAD

**Issue by m1q** [Hamza5/Learn-to-program-with-C_AR#35]
في مشكلة في الفهرس 
 الموشرات او pointers
مكتوب في الفهرس في الصفحة 129 و الصحيح في صفحة 135

**Comment by Hamza5** [comment]
يبدو أن المشكل ليس من تلك الصفحة فقط و إنّما من البداية، لأن صفحة الغلاف تعتبر الصفحة رقم 1 (لكن من المفروض أن الصفحة الأولى هي التقديم). هذا المشكل قد حدث في المرحلة الأخيرة من تجميع الكتاب لأني كنت أحرص على ترقيم الصفحات بشكل صحيح منذ البداية، هذا يعني أن علينا تغيير طريقة التجميع، سوف أرى مالّذي يمكننا فعله بخصوص هذا الأمر.
شكرا لك.

**Comment by Hamza5** [comment]
تم حل المشكلة، ستتوفر النسخة التالية قريبا.
