### ISSUE TITLE
رسالة شكر وتقدير

### ISSUE THREAD

**Issue by Asux30** [Hamza5/Learn-to-program-with-C_AR#36]
السلام عليكم
أشكر القائمين على هذا العمل الجبار في إغناء المكتبة العربية في مجال البرمجة وبالخصوص لغة البرمجة سي

فجزاكم الله خيرا

**Comment by Hamza5** [comment]
<div dir='rtl'>

نشكرك على التشجيع، و نأمل أن هذا ليس سوى البداية فقط.

بعد إذنك، سأغلق هذه العلّة لأنّها لا تتضمّن أيّة مشكلة.

</div>
