### ISSUE TITLE
شكر و طلب

### ISSUE THREAD

**Issue by taaleemy** [Hamza5/Learn-to-program-with-C_AR#41]
اشكرك جدا و لكن اريد ترجمة الي الانجليزية ضروري جدا

**Comment by Hamza5** [comment]
هذا الكتاب ليس فيه نسخة إنجليزية، والنسخة الأصلية منه فرنسية. لكن كتب الـC المكتوبة بالإنجليزية أكثر من أن تحصى ويمكنك إيجاد العشرات بل ربما المئات منها.
